Relationship converter new
jamasoftware-ps/RelationshipConverter pull request #2
Opened 2023-05-24 15:34 UTC by bmiller-jama

Updated PR for Python Relationship Converter without all the Python dependencies/packages

2023-06-21 18:16 UTC, nmchale-jama requested changes
Please remove the get pip .py f ile

2023-06-21 18:16 UTC, nmchale-jama commented on get-pip.py
delete this file from repo and rm from git

2023-06-21 18:18 UTC, nmchale-jama commented
Plase create a requiremetns.txt file via pip freeze

2023-06-21 18:18 UTC, nmchale-jama commented
Also please upadte the readme to reflect new dependencies and how to install via pip

2023-06-26 18:42 UTC, trobinson-jama commented on requirements.txt
> +py-jama-rest-client==1.16.0
Changed py rest client to 1.17.1

2023-06-26 21:11 UTC, trobinson-jama approved these changes

2023-06-26 21:12 UTC, trobinson-jama approved these changes

2023-06-26 21:13 UTC, merged